export const GET_REALTIME_ROOMS = "GET_REALTIME_ROOMS";
export const GET_REALTIME_USERS = "GET_REALTIME_USERS";

export const FILTER_ROOMS = "FILTER_ROOMS";
export const FILTER_USERS = "FILTER_USERS";
