export const SET_REALTIME_ROOMS = "SET_REALTIME_ROOMS";
export const SET_REALTIME_USERS = "SET_REALTIME_USERS";
export const GET_LOGGED_USER_DATA = "GET_LOGGED_USER_DATA";

export const SET_UNREAD_ROOM_MESSAGES = "SET_UNREAD_ROOM_MESSAGES";
export const FILTER_ROOMS = "FILTER_ROOMS";
export const FILTER_USERS = "FILTER_USERS";
export const TOGGLE_SIDEBAR_VIEW = "TOGGLE_SIDEBAR_VIEW";
export const SET_WINDOW_WIDTH = "SET_WINDOW_WIDTH";
